### ISSUE TITLE
SBML import fails with MATLAB R2018a

### ISSUE THREAD

**Issue by thomassligon** [AMICI-dev/AMICI#303] opened 2018-05-15 15:52 UTC
The attached file was created in Cell Designer and validated by SBML.org, but ODE import fails with

```
Error using sym>convertChar (line 1448)
Character vectors and strings in the first argument can only specify a variable or number. To evaluate character vectors and strings representing symbolic
expressions, use 'str2sym'.

Error in sym>tomupad (line 1214)
        S = convertChar(x);

Error in sym (line 211)
                S.s = tomupad(x);

Error in cell2sym (line 31)
Csym = cellfun(conv, C, 'UniformOutput', false);

Error in sym>tomupad (line 1226)
    xsym = cell2sym(x);

Error in sym (line 211)
                S.s = tomupad(x);

Error in SBMLode/importSBML>cleanedsym (line 686)
csym = sym(sanitizeString(strrep(str,'time','__time_internal_amici__')));

Error in SBMLode/importSBML (line 80)
all_rulemath = cleanedsym({model.rule.formula});

Error in SBMLode (line 63)
            model.importSBML(filename);

Error in testAsthmaM07cd2>import (line 57)
    ODE = SBMLode([modelName '.xml']);

Error in testAsthmaM07cd2 (line 10)
ODE = import(modelName); % only first time
```
[ODEimportError.zip](https://github.com/ICB-DCM/AMICI/files/2005694/ODEimportError.zip)

**Comment by dweindl** [comment] 2018-05-15 19:18
@thomassligon The script fails because of a wrong filename (ASTHMA_V40_M07cd vs ASTHMA_V40_M07cd2). 

After correcting that, sbml import works. Cannot reproduce this error wit the latest AMICI version on R2017b/Linux.

**Comment by thomassligon** [comment] 2018-05-15 20:15
Daniel, thanks for the quick response! I see that I uploaded the wrong script, cd2 instead of cd, so that (trivial) problem is fixed. In addition, if ODE import and amiwrap works, then everything is OK. However, I just retested, and I still get the same error. I am running R2018a/Windows. Could you try with R2018a/Linux?

**Comment by thomassligon** [comment] 2018-05-15 20:57
I just retested on R2017b/Windows and it seems to be working OK, except that I am getting tons of this warning:
```
Warning: Support of character vectors will be removed in a future release. Character vectors can be used only for variable names and numbers. Instead, to
create symbolic expressions first create symbolic variables using 'syms'. To evaluate character vectors and strings representing symbolic expressions, use
'str2sym'. 
```
Maybe R2018a is the future release they were talking about.

**Comment by dweindl** [comment] 2018-05-16 07:31
Thanks for testing with the old release. I don't have R2018a one installed at the moment. I didn't find any information on syms-related issues in mathworks release notes, but I guess you are right.

**Comment by dweindl** [comment] 2018-05-16 07:54
Reproduced with R2018a/Linux

**Comment by thomassligon** [comment] 2018-05-23 16:34
Please add my account (thomassligon) as a contributor. I would like to create a new branch and pull request for corrections to issue #303, since the latest changes did not fix it.

**Comment by FFroehlich** [comment] 2018-05-23 16:37
done

**Comment by thomassligon** [comment] 2018-05-28 13:35
I just fetched AMICI and tested, resulting the following error:

Undefined function or variable 'betterSym'.

Error in SBMLode/importSBML>cleanedsym (line 689)
csym = betterSym(sanitizeString(strrep(str,'time','__time_internal_amici__')));

**Comment by dweindl** [comment] 2021-03-09 10:13
By now, the documentation clearly states that we require Matlab<R2018a. Therefore, I think we can close this issue.

**Closed by dweindl** 2021-03-09 10:13 UTC
Labels: bug, matlab, wontfix
