### ISSUE TITLE
Error during sensitivity computation

### ISSUE THREAD

**Issue by lorenapohl** [AMICI-dev/AMICI#1501] opened 2021-04-25 16:32 UTC
I am getting errors when computing model sensitivities using `runAmiciSimulation` with a model specified in PETab. Specifically, the error is

`[Warning] AMICI:Inf: AMICI encountered an Inf value at index 0/8 in sxdot!`

A working example of the problem including the PETab files is here: [reproduce_issue.zip](https://github.com/AMICI-dev/AMICI/files/6372359/reproduce_issue.zip). `reproduce_issue.py` fails after printing the above error 37 times. I am using the Python interface and Amici version 0.11.14 on Ubuntu 20.04. 

There are Dirac delta functions appearing in `Oliveira_Nat2021_interior_dwdp.cpp`, but I am not certain they are the problem. Any support regarding the cause of this error and how to resolve it is greatly appreciated. Thanks in advance!

**Comment by FFroehlich** [comment] 2021-04-26 15:06
Thanks for reporting this and the example to reproduce the issue! This definitely sounds like a bug during model import. I will have a closer look!

**Comment by FFroehlich** [comment] 2021-04-26 17:50
Okay, the issue is that `https://github.com/AMICI-dev/AMICI/blob/57a7b11cc2fb301cf838daefd966830c522643a8/python/amici/ode_export.py#L1639` generates expressions before https://github.com/AMICI-dev/AMICI/blob/57a7b11cc2fb301cf838daefd966830c522643a8/python/amici/ode_export.py#L1668 processes and removes the heavisides in those expressions. @dilpath could you have a look how to best fix this?

**Comment by dweindl** [comment] 2021-05-30 18:03
Should be fixed in `v0.11.17`.

**Closed by dweindl** 2021-05-30 18:03 UTC
Labels: bug, fixed but not released, new
